### ISSUE TITLE
Listen for DCCppOverTCP server zeroconf broadcast

### ISSUE THREAD

**Issue by mstevetodd** [JMRI/EngineDriver#1099]
JMRI has a feature called DCCppOverTCP Server that can be used to connect EngineDriver (and EX-Toolbox) wifi clients to a DCC-EX system over USB (or other). This allows a DCC-EX system with no wifi to support wifi clients in DCC-EX protocol mode.
JMRI is already sending out the broadcast (see message in log):
`Starting ZeroConfService _dccppovertcpserver._tcp.local for DCCppOverTCP Server`
But EngineDriver is not (yet) listening for a broadcast with that name.  I suggest we add support for this broadcast to ED (and EX-Toolbox)
Since only DCC-EX protocol is supported, I suggest that this listen only occur when the proper preference is set.
(Conversely, the WiThrottle broadcast should probably be ignored if DCC-EX protocol is set to "yes".)

**Comment by flash62au** [comment]
Unfortunately EX-CS only broadcasts the WiThrottle service for either/both native and WiThrottle, so we can't ignore it.

**Comment by mstevetodd** [comment]
Peter completed this with PR #1100 
Works great, see screenshot.
![Uploading image.png…]()
