### ISSUE TITLE
More responsive/Material UI?

### ISSUE THREAD

**Issue by k4kfh** [JMRI/EngineDriver#19]
I love the utility of engine driver, but the UI looks a little dated. I understand features are probably the main priority (rightfully so) but perhaps a more modern, responsive UI that applies Google's Material Design would be useful. The interface on tablets could use a refresh, for example I'd like to be able to view a panel easily, and on a larger screen control more than two locomotives at a time.

**Comment by mstevetodd** [comment]
Thanks for the feedback, Hampton.

We're always open to PRs if you'd like to give the UI an overhaul. UI updates are extremely time-consuming for me, and I just don't have the time to invest.

There are some Preferences that you should try. In particular, the AutoWeb rotation preference is used by many to easily flip back and forth between the web view and the throttle view, and the "Number of Throttles" which can be set to 3.

**Comment by k4kfh** [comment]
I completely understand why you haven't focused on UI updates. The app is still very usable, and I'm glad you've developed it this far.

I'm new to Android development, but I plan on messing around with it a little bit, so I'll fork and submit a PR if I get anywhere with it.

Thanks for the tips on preferences, that fixes several of my problems.
