### ISSUE TITLE
Digitrax LnWi issue with 2.17

### ISSUE THREAD

**Issue by McLae** [JMRI/EngineDriver#201]
version 2.17 seems to have broken the connection to Digitrax LnWi. 
Worked before the update, does not work now.
Could someone do some testing to see what changed and how to get this back working?

**Comment by flash62au** [comment]
Hi,
can you provide a more detailed description of the issue?

Have you tried reinstalling v1.16 to confirm that 1.17 is the issue?  It
can be downloaded from here... https://enginedriver.mstevetodd.com/downloads

Peter Akers

**Comment by mstevetodd** [comment]
@McLae are you still having this issue with 2.18.1? I have an LnWi and it does not crash. If you are still having the issue with 2.18.1, please advise steps to reproduce.

**Comment by mstevetodd** [comment]
I've not heard back from @McLae, and I've verified 2.18.1 is working well with my LnWi. Closing.
