### ISSUE TITLE
Request ability to set long press time to swap direction buttons

### ISSUE THREAD

**Issue by KenNinomiya** [JMRI/EngineDriver#215]
If possible, it would be useful to allow a user to set the long press time to swap the two direction buttons.

We had a couple users at our last op session who accidentally changed button positions. A longer press time would help prevent that.

If it can be set to a user's preference, that would be ideal.

If not possible to give custom adjustment, increasing the long press to at least a couple seconds might help prevent accidental swaps.

Ken Ninomiya
Oxnard, CA

**Comment by flash62au** [comment]
Ken,
I should be able to do something in that space.

Peter Akers

**Comment by KenNinomiya** [comment]
Peter,

Just had notice from the members of the ops group who had the issues with accidental direction button changes. They informed me that ED 2.18.1 contained the long press adjustment option and it works well.

Thank you,

Ken

Ken Ninomiya
Oxnard, CA

**Comment by flash62au** [comment]
Thanks for the feedback.

Peter
