### ISSUE TITLE
Increase targetSdkVersion to 26

### ISSUE THREAD

**Issue by mattharris** [JMRI/EngineDriver#363]
Due to changed Play Store policies, the targetSdkVersion has to be changed to API 26 or later as we'll be unable to publish to the Play Store after 1st November 2018 - source:

https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

**Comment by mattharris** [comment]
One of the key items that will affect us is the removal of Apache HTTP Client since API 23. We have two options:

1. Migrate to HttpURLConnection
2. Keep using Apache via importing the legacy Apache HTTP Client library

For now, option 2 seems the most pragmatic option as this can be managed with minimal effort.

**Comment by mattharris** [comment]
Another item that we need to consider is the changed behaviour with regard application permissions.

As from API 23, we need to check for permissions at runtime as it is possible for them to be revoked by the user.

Further details on this (and other changes to be considered) are at https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by mattharris** [comment]
@mstevetodd I think we can close this now, agreed?

**Comment by mstevetodd** [comment]
@mattharris Yes, definitely. Thank you for your excellent efforts on this.
