### ISSUE TITLE
Licensing prompt when using on closed network

### ISSUE THREAD

**Issue by rhwood** [JMRI/EngineDriver#510]
While at a public show, when attempting to use EngineDriver, the attached was displayed on the user's Kindle only when attempting to use EngineDriver and no other application:

![IMG_0164](https://user-images.githubusercontent.com/297232/64950823-4d71e480-d84a-11e9-99f6-4bf8fcbc1d8f.JPG)

Is there any reason we need to check a license?

**Comment by mstevetodd** [comment]
I'm pretty sure that message is not coming from EngineDriver, but I'll scan the source later today to be sure.
What version of EngineDriver, and where was it installed from?

**Comment by cykodelic** [comment]
Not sure of the version, but it says Engine Drive 6462 at the bottom of the screen. It's on a Kindle.

**Comment by mstevetodd** [comment]
The EngineDriver version is shown on the About page of the app.

The app can be installed from the Amazon AppStore, the Google Play Store, or downloaded directly from the EngineDriver website. I'm going to assume you installed it from the Amazon AppStore (see next).

A quick Google search for that message text turns up messages of this nature: https://www.amazonforum.com/forums/devices/fire-tablets/515165-can-i-switch-off-the-need-to-refresh-the-licence

So it seems that the Amazon store itself is requiring you to periodically connect to the Internet. I could find no mention of this in the Amazon Developer Console.

**Comment by cykodelic** [comment]
Thanks! Got it done.
mark
