### ISSUE TITLE
Feature request: new connection profile for Roco / Fleischmann Multimaus

### ISSUE THREAD

**Issue by Alan-RMA49** [JMRI/EngineDriver#779]
Issue:

Following discussions on the group, it seems the code in older Roco / Fleischmann Multimaus controllers is non-compliant with the XpressNet 3.6 standard, meaning they can't interpret the (compliant) commands issued by JMRI for F13 to F28. This excludes JMRI from contexts where these controllers are used with locomotives that are sound fitted or have custom function mapping. A custom connection profile for this hardware that transmits the expected (wrong) code to the MultiMaus should resolve the issue. I have one of these that's connected to JMRI via a Lenz XpressNet 3.6 module, is there any way I can get JMRI to record the actual commands being issued by the controller for F13 - F28 so I can report back here?

Background:

Multimaus controllers are widely-used in Europe and can regularly be seen at shows and exhibitions. Our club has six or seven of them, and a number of our members have their own at home. The v1.05 firmware enables functions F13 to F28 via a double-press of the Shift key, and these functions work fine when the controllers are being used independently or connected as slaves to a Roco z21 command station (the code for which presumably takes this code defect into account). 

Multimaus users on a German forum investigated the issue back in 2011 and reported it to Roco who acknowledged it, but the last firmware update was issued in 2013 and doesn't address it. As the hardware is no longer supported, there's little chance it'll ever be fixed by Roco. 

Extract & Google translation translation from https://www.h0-modellbahnforum.de/t320276f19606-Multimaus-mit-LZV-wie-Funktionen-ab-F-1.html

**_So, I examined the multimouse with the sniffer.
F13 enters:
E4 F3 AH AL 01 PB,
according to Lenz (Docu 3.6) this should be:
E4 23 AH AL 01 PB_**

**_So the Lokmaus sends a wrong X-Bus command to the LZV, which cannot do anything with it and does nothing to be on the safe side.
Wait for MM update..._**

Cheers,

Alan

**Comment by mattharris** [comment]
@Alan-RMA49 Can you move this issue to the [JMRI/JMRI](https://github.com/JMRI/JMRI) repository please as this is more relevant for the main codebase.

Thanks.

**Comment by Alan-RMA49** [comment]
Whoops, didn't check which repository I was in before posting... 

Done: https://github.com/JMRI/JMRI/issues/9335
